### ISSUE TITLE
Bash error: cannot set terminal process group. Inappropriate ioctl for device

### ISSUE THREAD

**Issue by jfsiii** [sindresorhus/alfred-npms#1]
I downloaded the workflow from http://www.packal.org/workflow/npms-0 and installed it, but I cannot get the search to work.

Typing `npm <enter>` shows the expected screen <img width="604" alt="screen shot 2016-06-27 at 9 47 10 am" src="https://cloud.githubusercontent.com/assets/57655/16388062/48753c90-3c4c-11e6-80d7-ca8ab518dd90.png"> 

but any typing after that turns into a "normal" alfred search <img width="581" alt="screen shot 2016-06-27 at 9 48 27 am" src="https://cloud.githubusercontent.com/assets/57655/16388080/58bbf9ea-3c4c-11e6-9257-49f0628b45fd.png">

I went into the workflow debugger and noticed the following debug output with each keystroke

```
Starting debug for 'npms'

[2016-06-27 09:42:47][ERROR: input.scriptfilter] Code 127: bash: cannot set terminal process group (18927): Inappropriate ioctl for device
bash: no job control in this shell
/Users/jschulz/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Scripts/BAA37249-3FCB-4A17-8851-29707885B376: line 9: node: command not found
```

`node` is installed. I'm assuming that's a cascading failure originating from the `cannot set terminal process group` error.

Let me know if I can do anything else to help debug or fix.

I followed the same steps and get the same behavior for https://github.com/sindresorhus/alfred-emoj. Let me know if you'd like me to open an issue there, as well.

**Comment by sindresorhus** [comment]
How did you install Node.js? See for what kind of debug info I need: https://github.com/sindresorhus/alfred-emoj/issues/1

**Comment by sindresorhus** [comment]
In the script filter code in the `npms` workflow, can you try removing the `i` in `-ic`?

**Comment by jfsiii** [comment]
That reduces the output to `[2016-06-27 17:59:25][ERROR: input.scriptfilter] Code 127: env: node: No such file or directory`

Here's `PATH` when the script is run (with only -c): `/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin`

`node` doesn't exist under any of those directories, so `no such file or directory` makes sense. It's under a directory which is added to `$PATH` during login (`~/.bash_profile`) which, IIUC, is what the `-i` is for.

Also tried changing script to:

```
if [ -x /usr/libexec/path_helper ]; then
    eval `/usr/libexec/path_helper -s`
fi
if  [ -f "$HOME"/.profile ]; then
    source "$HOME"/.profile
elif [ -f "$HOME"/.bash_profile ]; then
    source "$HOME"/.bash_profile
elif [ -f "$HOME"/.bashrc ]; then
    source "$HOME"/.bashrc
fi

export PATH=/usr/local/bin:$PATH

NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

node index.js "$1"
```

but that generated

```
[2016-06-27 18:37:00][ERROR: input.scriptfilter] JSON error: JSON text did not start with array or object and option to allow fragments not set. in JSON:
(B[m]1337;RemoteHost=jschulz@tw-mbp13-jschulz]1337;CurrentDir=/Users/jschulz/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.EBB42F15-4CE2-4735-8F7D-853BCB109BE4]1337;ShellIntegrationVersion=1{"items":[{"title":"d3","subtitle":"A JavaScript visualization library for HTML and SVG.","arg":"https://github.com/mbostock/d3","mods":{"alt":{"arg":"https://www.npmjs.com/package/d3","subtitle":"Open the npm page instead of the GitHub repo"}},"quicklookurl":"https://github.com/mbostock/d3#readme"},{"title":"d3-queue","subtitle":"Evaluate asynchronous tasks with configurable concurrency.","arg":"https://github.com/d3/d3-queue","mods":{"alt":{"arg":"https://www.npmjs.com/package/d3-queue","subtitle":"Open the npm page instead of the GitHub repo"}},"quicklookurl":"https://github.com/d3/d3-queue#readme"},{"title":"d3-scale","subtitle":"Encodings that map abstract data to visual representation.","arg":"https://github.com/d3/d3-scale","mods":{"alt":{"arg":"https://www.npmjs.com/package/d3-scale","subtitle":"Open the npm page instead of the GitHub repo"}},"quicklookurl":"https://github.com/d3/d3-scale#readme"},{"title":"d3-shape","subtitle":"Graphical primitives for visualization, such as lines and areas.","arg":"https://github.com/d3/d3-shape","mods":{"alt":{"arg":"https://www.npmjs.com/package/d3-shape","subtitle":"Open the npm page instead of the GitHub repo"}},"quicklookurl":"https://github.com/d3/d3-shape#readme"},{"title":"three","subtitle":"JavaScript 3D library","arg":"https://github.com/mrdoob/three.js","mods":{"alt":{"arg":"https://www.npmjs.com/package/three","subtitle":"Open the npm page instead of the GitHub repo"}},"quicklookurl":"https://github.com/mrdoob/three.js#readme"},{"title":"d3-color","subtitle":"Color spaces! RGB, HSL, Cubehelix, Lab and HCL (Lch).","arg":"https://github.com/d3/d3-color","mods":{"alt":{"arg":"https://www.npmjs.com/package/d3-color","subtitle":"Open the npm page instead of the GitHub repo"}},"quicklookurl":"https://github.com/d3/d3-color#readme"},{"title":"gulp-rev","subtitle":"Static asset revisioning by appending content hash to filenames: unicorn.css => unicorn-d41d8cd98f.css","arg":"https://github.com/sindresorhus/gulp-rev","mods":{"alt":{"arg":"https://www.npmjs.com/package/gulp-rev","subtitle":"Open the npm page instead of the GitHub repo"}},"quicklookurl":"https://github.com/sindresorhus/gulp-rev#readme"},{"title":"d3-selection","subtitle":"Data-driven DOM manipulation: select elements and join them to data.","arg":"https://github.com/d3/d3-selection","mods":{"alt":{"arg":"https://www.npmjs.com/package/d3-selection","subtitle":"Open the npm page instead of the GitHub repo"}},"quicklookurl":"https://github.com/d3/d3-selection#readme"},{"title":"d3-interpolate","subtitle":"Interpolate numbers, colors, strings, arrays, objects, whatever!","arg":"https://github.com/d3/d3-interpolate","mods":{"alt":{"arg":"https://www.npmjs.com/package/d3-interpolate","subtitle":"Open the npm page instead of the GitHub repo"}},"quicklookurl":"https://github.com/d3/d3-interpolate#readme"},{"title":"d3-array","subtitle":"Array manipulation, ordering, searching, summarizing, etc.","arg":"https://github.com/d3/d3-array","mods":{"alt":{"arg":"https://www.npmjs.com/package/d3-array","subtitle":"Open the npm page instead of the GitHub repo"}},"quicklookurl":"https://github.com/d3/d3-array#readme"},{"title":"d3-format","subtitle":"Format numbers for human consumption.","arg":"https://github.com/d3/d3-format","mods":{"alt":{"arg":"https://www.npmjs.com/package/d3-format","subtitle":"Open the npm page instead of the GitHub repo"}},"quicklookurl":"https://github.com/d3/d3-format#readme"},{"title":"pretty-ms","subtitle":"Convert milliseconds to a human readable string: 1337000000 → 15d 11h 23m 20s","arg":"https://github.com/sindresorhus/pretty-ms","mods":{"alt":{"arg":"https://www.npmjs.com/package/pretty-ms","subtitle":"Open the npm page instead of the GitHub repo"}},"quicklookurl":"https://github.com/sindresorhus/pretty-ms#readme"},{"title":"d3-ease","subtitle":"Easing functions for smooth animation.","arg":"https://github.com/d3/d3-ease","mods":{"alt":{"arg":"https://www.npmjs.com/package/d3-ease","subtitle":"Open the npm page instead of the GitHub repo"}},"quicklookurl":"https://github.com/d3/d3-ease#readme"},{"title":"d3-time-format","subtitle":"A JavaScript time formatter and parser inspired by strftime and strptime.","arg":"https://github.com/d3/d3-time-format","mods":{"alt":{"arg":"https://www.npmjs.com/package/d3-time-format","subtitle":"Open the npm page instead of the GitHub repo"}},"quicklookurl":"https://github.com/d3/d3-time-format#readme"},{"title":"d3-time","subtitle":"A calculator for humanity’s peculiar conventions of time.","arg":"https://github.com/d3/d3-time","mods":{"alt":{"arg":"https://www.npmjs.com/package/d3-time","subtitle":"Open the npm page instead of the GitHub repo"}},"quicklookurl":"https://github.com/d3/d3-time#readme"},{"title":"d3-dsv","subtitle":"A parser and formatter for delimiter-separated values, such as CSV and TSV","arg":"https://github.com/d3/d3-dsv","mods":{"alt":{"arg":"https://www.npmjs.com/package/d3-dsv","subtitle":"Open the npm page instead of the GitHub repo"}},"quicklookurl":"https://github.com/d3/d3-dsv#readme"},{"title":"d3-dispatch","subtitle":"Register named callbacks and call them with arguments.","arg":"https://github.com/d3/d3-dispatch","mods":{"alt":{"arg":"https://www.npmjs.com/package/d3-dispatch","subtitle":"Open the npm page instead of the GitHub repo"}},"quicklookurl":"https://github.com/d3/d3-dispatch#readme"}]}
```

My workaround for now is changing the script to `/path/to/node index.js "$1"` and everything works as expected.

**Comment by sindresorhus** [comment]
@silverwind Any idea why `-i` wouldn't be working?

**Comment by sindresorhus** [comment]
@jfsiii It doesn't work because it seems your dotfiles print "�(B�[m�]1337;RemoteHost=jschulz@tw-mbp13-jschulz��]1337;CurrentDir=/Users/jschulz/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.EBB42F15-4CE2-4735-8F7D-853BCB109BE4��]1337;ShellIntegrationVersion=1�" which interfere with output sent to Alfred. Wonder if there's any way we could suppress that.

> It's under a directory which is added to $PATH during login

Why? Are you using a version manager or something?

**Comment by paulmolluzzo** [comment]
@jfsiii can you try this to see if it works? Notice the last `/` in the `PATH` being exported.

```
export PATH=/usr/local/bin/:$PATH

node index.js "$1"
```

This is the solution I found for `alfred-emoj` here: https://github.com/sindresorhus/alfred-emoj/issues/2#issuecomment-228929295. It is also working for me here on `alfred-npms`

**Comment by sindresorhus** [comment]
@paulmolluzzo That doesn't help as he doesn't have node installed there. The `/` doesn't do anything.

**Comment by paulmolluzzo** [comment]
> That doesn't help as he doesn't have node installed there.

@sindresorhus OK, I see. Really you could install node anywhere. Running `which node` will get the direct path, so maybe that's a simpler way to get node instead of loading the entire PATH.

**Comment by sindresorhus** [comment]
@paulmolluzzo If `which node` works, `node` works. Both has to be run in a shell with the correct $PATH, which my script is trying to solve.

**Comment by sindresorhus** [comment]
It's clear that `$($(echo $SHELL) -ic 'echo $PATH')` needs to be run so that errors are ignored.

**Comment by steelbrain** [comment]
@sindresorhus the `$SHELL -ic` method is buggy, unpredictable and unreliable, in my [consistent-env](https://github.com/steelbrain/consistent-env), I replaced it with the good ol' source, see [`src/helpers#94`](https://github.com/steelbrain/consistent-env/blob/2351cb1261c79eda27d028174161e8b2249f599c/src/helpers.js#L94). Haven't had any PATH related bug reports on linters after that

**Comment by silverwind** [comment]
Not sure I wanna dig into shell source to find out about `-i`, but actively sourcing things like `/etc/profile`, `~/profile`, `~/.zshenv`, `~/.zshrc` might be one way to get the full env.

**Comment by sindresorhus** [comment]
@steelbrain How do you handle the case of something printing when being sourced? See: https://github.com/sindresorhus/alfred-npms/issues/1#issuecomment-229016267

**Comment by sindresorhus** [comment]
> is buggy, unpredictable and unreliable

Computers and software in general... Especially archaic things like shells and $PATH.

**Comment by paulmolluzzo** [comment]
> How do you handle the case of something printing when being sourced? See: #1 (comment)

@sindresorhus Maybe try sending the results to `dev/null` like `source .bashrc &> /dev/null`?

**Comment by silverwind** [comment]
@jfsiii: Looking through bash source, I could see an obstacle if bash was launched in `sh` compatibilty mode (I think this is equvialent to [POSIX mode](http://www.gnu.org/software/bash/manual/html_node/Bash-POSIX-Mode.html)), which does not source `.bashrc`. Can you check if the `POSIXLY_CORRECT` environment variable is present?

**Comment by sindresorhus** [comment]
Ok, here's what I got. Could use some feedback:

```sh
{
	if [ -x /usr/libexec/path_helper ]; then
		eval $(/usr/libexec/path_helper -s)
	fi

	if [ $SHELL == "/bin/zsh" ]; then
		# sourcing both as people commonly define PATHs in both...
		if [ -f "$HOME/.zshenv" ]; then
			# TODO: DRY this up. Lots of duplication.
			PATH=$($SHELL -c 'source $HOME/.zshenv;echo $PATH'):$PATH
		fi

		if [ -f "$HOME/.zshrc" ]; then
			PATH=$($SHELL -c 'source $HOME/.zshrc;echo $PATH'):$PATH
		fi
	elif [ $SHELL == "/bin/bash" ]; then
		if [ -f "$HOME/.profile" ]; then
			PATH=$($SHELL -c 'source $HOME/.profile;echo $PATH'):$PATH
		elif [ -f "$HOME/.bash_profile" ]; then
			PATH=$($SHELL -c 'source $HOME/.bash_profile;echo $PATH'):$PATH
		elif [ -f "$HOME/.bashrc" ]; then
			PATH=$($SHELL -c 'source $HOME/.bashrc;echo $PATH'):$PATH
		fi
	fi
	# TODO: support Fish shell too

	# always add this, as it's the most likely location, unless NVM is used
	PATH=/usr/local/bin:$PATH

	if [ -d "$HOME/.nvm" ]; then
		source "$HOME/.nvm/nvm.sh"
	fi
}
#&>/dev/null # silence any output when sourcing

if command -v node >/dev/null 2>&1; then
	node index.js "$1"
else
	echo $'{"items":[{"title": "Couldn\'t find the `node` binary", "subtitle": "Symlink it to `/usr/local/bin`"}]}'
fi
```

-

// @mafredri

**Comment by silverwind** [comment]
The plot thickens, turns out bash has 5 different modes with different startup files sourced in each mode. I guess the fact that macOS sources `/etc/profile` when interactive must be a Apple-specific path to bash:

http://wiki.bash-hackers.org/scripting/bashbehaviour

**Comment by paulmolluzzo** [comment]
Related: http://www.joshstaiger.org/archives/2005/07/bash_profile_vs.html

**Comment by silverwind** [comment]
There's an interesting bit in above link:

> An exception to the terminal window guidelines is Mac OS X’s Terminal.app, which runs a login shell by default for each new terminal window

If this is correct, it should yield better paths when bash is launched with `-l`insteadof `-i` on macOS. Can anyone affected confirm?

**Comment by jfsiii** [comment]
@silverwind replacing `-i` with `-l` works without issue.

**Comment by paulmolluzzo** [comment]
@jfsiii can you paste your entire script filter please?

**Comment by jfsiii** [comment]
@paulmolluzzo 

```
# various tricks to get the user's PATH
# PATH is not set when run from GUI apps on macOS
eval $(/usr/libexec/path_helper -s)
export PATH=/usr/local/bin:$($(echo $SHELL) -lc 'echo $PATH'):$PATH

NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

node index.js "$1"
```

**Comment by jfsiii** [comment]
@sindresorhus I tried the new script, but end up in the *Couldn't find the \`node` binary*  branch ![screen shot 2016-06-29 at 10 29 29 am](https://cloud.githubusercontent.com/assets/57655/16462101/9e2166ca-3de4-11e6-9372-7bfcaeddd7cb.png)

**Comment by paulmolluzzo** [comment]
@jfsiii thank you.

The same filter does not work for me. Instead I get this error:

```
[2016-06-29 13:29:25][STDERR: input.scriptfilter] stty: stdin isn't a terminal
/Users/paul/dotfiles/aliases/random.sh: line 106: bind: warning: line editing not enabled
[2016-06-29 13:29:25][input.scriptfilter] {"items":[{"title":"HTTPError","subtitle":"Response code 400 (Bad Request)","valid":false,"text":{"copy":"HTTPError: Response code 400 (Bad Request)\n    at stream.catch.then.e (/Users/paul/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.C8559ED2-74BF-47E2-8B0A-9B5465B9BBCA/node_modules/got/index.js:114:13)\n    at process._tickCallback (internal/process/next_tick.js:103:7)"}}]}
```

My `.bashrc` does `source`  a script that uses `bind`. When I comment out that line I still get an error:

```
[2016-06-29 13:30:57][STDERR: input.scriptfilter] stty: stdin isn't a terminal
[2016-06-29 13:30:57][input.scriptfilter] {"items":[{"title":"HTTPError","subtitle":"Response code 400 (Bad Request)","valid":false,"text":{"copy":"HTTPError: Response code 400 (Bad Request)\n    at stream.catch.then.e (/Users/paul/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.C8559ED2-74BF-47E2-8B0A-9B5465B9BBCA/node_modules/got/index.js:114:13)\n    at process._tickCallback (internal/process/next_tick.js:103:7)"}}]}
```

**Comment by jfsiii** [comment]
@sindresorhus 

> > It's under a directory which is added to $PATH during login

> Why? Are you using a version manager or something?

Yes

**Comment by silverwind** [comment]
As a possible fix, I think `-ilc` instead of `-ic` should work for both bash and zsh. My regular shells on both macOS and Linux are both interactive and login:

```
$ bash -ilc "case $- in (*i*) echo interactive; esac; case $- in (*l*) echo login; esac;"
interactive
login
```
```
$ zsh -ilc "case $- in (*i*) echo interactive; esac; case $- in (*l*) echo login; esac;"
interactive
login
```

This tweak could also be useful for https://github.com/sindresorhus/shell-env

**Comment by jfsiii** [comment]
@silverwind I came back here to post the same thing. `-ilc`still causes the error from the description, but it's only visible in the debug log. There's nothing visibly wrong while using the workflow.

```
Starting debug for 'npms'

[2016-06-29 11:04:16][STDERR: input.scriptfilter] bash: cannot set terminal process group (40497): Inappropriate ioctl for device
bash: no job control in this shell
```

**Comment by mafredri** [comment]
> As a possible fix, I think -ilc instead of -ic should work for both bash and zsh. My regular shells on both macOS and Linux are both interactive and login:

Indeed, an interactive login shell should source all the possible locations automatically.

@sindresorhus If we should have different logic for different shells, I think it would benefit to not use the aboslute paths as there is no guarantees, e.g. `[ "$(basename $SHELL)" = zsh ]`.

Honestly I think the whole script should be condensable to:

```shell
export PATH="$($SHELL -i -l -c 'echo $PATH')"
```

Maybe leaving in the path helper and nvm is a good idea. But if these are working in the users own shell, I don't see why they shouldn't here.

Another radical idea would be to try all known shells, something like:

```shell
eval $(
    for shell in sh bash zsh fish; do
        if which $shell >/dev/null 2>&1; then
            $shell -i -l -c 'echo PATH=$PATH:\$PATH' | grep "^PATH="
        fi
    done
)
export PATH
```

The above takes into consideration that the spells might spit out nonsense during initialization, we only want the PATH(s) out of there.

**Comment by steelbrain** [comment]
@sindresorhus the case of it printing non-expected stuff is handled by a regex that only matches stuff like `KEY=VALUE`

**Comment by mafredri** [comment]
One potential problem is that you cant really trust the users default shell, for example say the default shell is `zsh`, but the contents of `.zshrc` is as follows:

`~/.zshrc`:
```shell
export PATH=/custom:$PATH
exec bash -l # hand over execution to bash
```

And thus `$SHELL -i -l -c 'echo $PATH'` would produce nothing, in fact, in this case it would open a new bash login shell that does not exit. At worst it produces nothing. And even when bash is executed directly, the user might rely on that custom PATH defined in the `.zshrc` 😃🔫.

**Comment by silverwind** [comment]
@mafredri that case could work with something like `bash "$@"` 😉

**Comment by mafredri** [comment]
@silverwind unfortunately we have no control of how the user has written their rc-files 😢. But this is hypothetical anyway, not sure if anyone actually does this, and if they do it's likely by accident or due to no knowledge of `chsh`.

**Comment by paulmolluzzo** [comment]
> likely by accident or due to no knowledge of chsh

@mafredi I would venture a guess that a fair number of bash `rc`/`profiles` are hobbled together by people with little knowledge or interest in knowing anything beyond "it works". If we want a worse hypothetical: We continue to presume everyone has node in their PATH at all. I wouldn't be totally shocked to see someone do something weird like `alias node=/absolute/path/to/node`. At least, I've seen weirder stuff.

**Comment by sindresorhus** [comment]
I'm looking for a best effort here. Not a perfect one. That would indeed be impossible.

**Comment by sindresorhus** [comment]
I would prefer

```
eval "$($SHELL -i -l -c 'echo PATH=$PATH:\$PATH' 2>/dev/null | grep "^PATH=")"
export PATH
```

 if it works for everyone?

**Comment by SamVerschueren** [comment]
The odd thing is that `echo "$($SHELL -i -l -c 'echo PATH=$PATH:\$PATH' 2>/dev/null | grep "^PATH=")"` isn't printing anything for me.

<img width="646" alt="screen shot 2016-06-30 at 14 01 42" src="https://cloud.githubusercontent.com/assets/1913805/16487562/092c9196-3ecc-11e6-9f60-1abf8a34c672.png">

However, if I remove the `^` in the regex, it shows me the correct path and it looks like `PATH=` is the first word of the string. But `grep` doesn't seem to agree on that. Is it possible that some ansi escape code is printed as first character? Maybe related to https://github.com/sindresorhus/fix-path/issues/6.

**Comment by SamVerschueren** [comment]
Removing the `-l` flag made the output work. Tried it in the `alfred-npms` script but didn't work.

**Comment by mafredri** [comment]
That is most likely some invisible character or escape code. You can check it with e.g.

```shell
echo "$($SHELL -i -l -c 'echo PATH=$PATH:\$PATH' 2>/dev/null | grep "PATH=" | hexdump -C)"
```

How about this for a fix?

```shell
eval "$($SHELL -i -l -c 'echo -e "\n"PATH=$PATH:\$PATH"\n"' 2>/dev/null | grep "^PATH=")"
"$(bash -i -l -c 'echo -e "\n"PATH=$PATH:\$PATH"\n"' 2>/dev/null)"
```

**Comment by SamVerschueren** [comment]
YES YES YES!!!

It was an invisible character:

![screen shot 2016-06-30 at 14 31 31](https://cloud.githubusercontent.com/assets/1913805/16488155/6610468e-3ecf-11e6-8ac8-fc4ce6b1aa1c.png)

I installed `strip-ansi-cli` and executed this command

```
$ echo "$($SHELL -i -l -c 'echo PATH=$PATH:\$PATH' 2>/dev/null | strip-ansi | grep "^PATH=")"
```

And that worked.

No I used your solution in `alfred-npms` and it worked.

```
eval $(/usr/libexec/path_helper -s)
eval "$($SHELL -i -l -c 'echo -e "\n"PATH=$PATH:\$PATH"\n"' 2>/dev/null | grep "^PATH=")"
export PATH

if command -v node >/dev/null 2>&1; then
    node index.js "$1"
else
    echo $'{"items":[{"title": "Couldn\'t find the `node` binary", "subtitle": "Symlink it to `/usr/local/bin`"}]}'
fi
```

**Comment by mafredri** [comment]
We should probably also quote the PATH, users might have spaces in their path:

```shell
eval "$($SHELL -i -l -c 'echo -e "\n"PATH=\"$PATH:\$PATH\""\n"' 2>/dev/null | grep "^PATH=")"
```

**Comment by sindresorhus** [comment]
Thanks for the help all 🍰✨ I've published a new version: http://www.packal.org/workflow/npms-0 Gonna keep this issue open until I'm confident we found a permanent solution.

**Comment by paulmolluzzo** [comment]
Can confirm this one works for me.

**Comment by jfsiii** [comment]
Works for me, as well. Thanks!
