### ISSUE TITLE
Add going to actual npm page of the npm package with a modifier key

### ISSUE THREAD

**Issue by nikitavoloboev** [sindresorhus/alfred-npms#15]
So for example if I search for express and press return, it would open the [github express page](https://github.com/expressjs/express).

But if I search for express and press cmd + return on it, it would open [npm page with express](https://www.npmjs.com/package/express).

It would be extremely useful for me, I hope it can be added. Thank you.

**Comment by SamVerschueren** [comment]
From the docs

> Hold Alt when pressing Enter to go to its npm page.
