### ISSUE TITLE
Searching a module fails

### ISSUE THREAD

**Issue by SamVerschueren** [sindresorhus/alfred-npms#16]
The API might have changed, not sure. But this is what I get if I search something.

![screen shot 2017-01-16 at 15 40 27](https://cloud.githubusercontent.com/assets/1913805/21987027/1ef16a5a-dc02-11e6-8a6e-6f9333e524b5.png)

**Comment by sindresorhus** [comment]
The npms.io API is down it seems: https://api.npms.io/v2/search?q=unicorn

**Comment by satazor** [comment]
Sorry, should be all good now!

**Comment by SamVerschueren** [comment]
@satazor It's failing again. Any idea?

**Comment by satazor** [comment]
@SamVerschueren yea disk went full. It's almost recored, I finally had some time to fix it. Meanwhile we will move to npmjs infra to avoid having disk space constraints.
