### ISSUE TITLE
Do you have plan to support npm registery?

### ISSUE THREAD

**Issue by popomore** [sindresorhus/alfred-npms#17]
We are using an enterprise registry served by https://github.com/cnpm/cnpmjs.org, and the API is compatable to npmjs.org. I want to use this workflow to search from our registry, but the result is different.

**Comment by sindresorhus** [comment]
Sorry, this is tied to the npms.io API, not npm. Should be pretty easy to fork and adapt it to your needs though.

**Comment by popomore** [comment]
OK
