### ISSUE TITLE
ERROR: input.scriptfilter

### ISSUE THREAD

**Issue by saneef** [sindresorhus/alfred-npms#19]
I installed this package and I could invoke the search from Alfred. But, after that it falls back to default search.

<img width="1182" alt="screenshot 2017-09-07 18 32 02" src="https://user-images.githubusercontent.com/81863/30164841-77f494b8-93fb-11e7-99e5-dbee744420da.png">

Here is log using Alfred's debugger: https://gist.github.com/saneef/eb94a57bfd744461e304da5af1a0ddcc

**Comment by SamVerschueren** [comment]
Can you run `node --version` in your terminal? It should be 4+.

**Comment by saneef** [comment]
Mine is `v8.3.0`

**Comment by SamVerschueren** [comment]
Can you remove the workflow and install it again? I bumped some packages downstream and I hope this solves the issue on newer node versions.

**Comment by saneef** [comment]
@SamVerschueren I did and it's working! Thanks
