### ISSUE TITLE
Bundle to single workflow file

### ISSUE THREAD

**Issue by muuvmuuv** [sindresorhus/alfred-npms#28]
Would be great if you would bundle it to a single workflow file. I use NVM and don't want to add alfred workflows in every version. This would get messy at some point.

**Comment by sindresorhus** [comment]
Sorry, not interested in doing that. Seems like your problem here is NVM, which should preserve global packages across Node.js versions.

**Comment by sindresorhus** [comment]
Actually, just make a directory somewhere, install this package locally there, and it will work ;)
