### ISSUE TITLE
Syncing across different Macs

### ISSUE THREAD

**Issue by fujeffrey1** [sindresorhus/alfred-npms#29]
This is a great workflow! The only issue for me is syncing across different machines since I'd like to use this on both my work and personal computers. From the Alfred docs, I've set up dropbox to keep my workflows consistent but installing this on one machine removes it from the other.

**Comment by sindresorhus** [comment]
I think this is because Dropbox stopped supporting symlinks, which we use.

Closing in favor of https://github.com/SamVerschueren/alfred-link/issues/25.

**Comment by tborychowski** [comment]
I have the same issue when using icloud sync. 
Is there a workaround?
Can this workflow be built into a portable package?
