### ISSUE TITLE
Publish on npm

### ISSUE THREAD

**Issue by vutran** [sindresorhus/alfred-npms#6]
Hi,

I'm looking to see if you can publish this module into npm as I have just recently developed [this](https://github.com/vutran/dext) app which is made to be compatible with existing *alfy* workflows. Right now it works with my own alfy module but would like to see if become fully compatible with other alfy modules.

**Comment by sindresorhus** [comment]
Yes, will be done very soon. See: https://github.com/sindresorhus/alfred-npms/pull/5
