### ISSUE TITLE
Install via NPM makes my Alfred Preferences unusable

### ISSUE THREAD

**Issue by kiliankoe** [sindresorhus/alfred-npms#8]
I installed the workflow as suggested via the readme using `npm install -g alfred-npms`. On opening my Alfred preferences all I get is a white window 😕 

Fortunately enough everything works again after uninstalling via npm.

**Comment by SamVerschueren** [comment]
Do you already have the `npms` package present in `Alfred` which was installed via Packal? If so, remove that one first. Alfred can't handle two workflows with identical names.

**Comment by kiliankoe** [comment]
Was just gonna comment that this is probably an issue with alfred-link instead^^

I don't have another npms workflow installed. I do have a custom search set up that takes "npms" as an argument. Can that get in the way as well?

**Comment by SamVerschueren** [comment]
Might be, not familiar with custom searches. Is it possible to remove that one and try again?

**Comment by kiliankoe** [comment]
I've tried, unfortunately to no avail. I'm not sure what could get into the way here.

**Comment by SamVerschueren** [comment]
What does this show you?

```
$ ls ~/Library/Application\ Support/Alfred\ 3/Alfred.alfredpreferences/workflows/
```

If you changed the workflow directory in Alfred preferences, `ls` that directory instead. I'm curious to see what's in there.

**Comment by kiliankoe** [comment]
A bunch of "user.workflow.id"s and alfred-npms as a symlink to `/usr/local/lib/node_modules/alfred-npms`, which doesn't seem to exist (anymore). 

Remove all the alfred-npms references and try installing again?

**Comment by SamVerschueren** [comment]
Yes try that. And you are 100% sure that one of those `user.workflow.id` doesn't have the `<key>name</key>` tag set to `npms`?

**Comment by kiliankoe** [comment]
Took a bit to figure out how to do that without just reading through Alfred :D

`find . -name "info.plist" -print0 | xargs -0 -L1 /usr/libexec/PlistBuddy -c "Print :name"`

Definitely no npms in that output.

**Comment by SamVerschueren** [comment]
Strange. Can you try installing [alfred-ng2](https://github.com/SamVerschueren/alfred-ng2). Still a white screen?

**Comment by kiliankoe** [comment]
That worked just fine. Umm... I'm not sure what to say. I have absolutely no clue why npms isn't working.

**Comment by SamVerschueren** [comment]
Aha, I know why! It's indeed an issue with `alfred-link`. At first, `alfred-link` added the `name` property dynamically. That behaviour was then removed and I did a patch release, which off course should've been a feature release. Let me fix that.

**Comment by SamVerschueren** [comment]
@kiliankoe Did a PR. Have to wait for @sindresorhus though as I can't release this workflow to npm.

**Comment by kiliankoe** [comment]
Thank you so much!

**Comment by SamVerschueren** [comment]
Well, thank you for letting me/us know :).
